CI/CD : deploy.yaml Fix

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -55,8 +55,13 @@ jobs:
           script_stop: true
           script: |
             curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscli-exe-linux-x86_64.zip"
-            unzip awscli-exe-linux-x86_64.zip
-            sudo ./aws/install
+            if [ -f "awscli-exe-linux-x86_64.zip" ]; then
+              unzip awscli-exe-linux-x86_64.zip
+              sudo ./aws/install
+            else
+              echo "Failed to download awscli-exe-linux-x86_64.zip"
+              exit 1
+            fi
             aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
             docker pull ${{ steps.login-ecr.outputs.registry }}/web-server:latest
             docker run -d --name web-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/web-server:latest
